linters:
  disable-all: true
  enable:
    # - staticcheck (used in bugs preset)

  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - style
    # - unused
    # - bugs

linters-settings:
  staticcheck:
    go: "1.13"

    checks: ["all"]

  unused:
    go: "1.13"

issues:
  include:
    - EXC0002
