linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
  presets:
    - bugs
    - unused

linters-settings:
  staticcheck:
    go: "1.13"

    checks: ["all"]

  unused:
    go: "1.13"

issues:
  include:
    - EXC0002