linters:
  disable-all: false
  enable:
    # - staticcheck (used in bugs preset)
  disable:
    - wsl # Readability
    - gomnd
    - lll
    - wrapcheck # Recommended
    - tagliatelle
    - gochecknoglobals
    - errcheck # Recommended
    - gosimple # Recommended
    - exhaustivestruct # Recommended
    - nlreturn # Recommended
    - stylecheck # Recommended
    - paralleltest
    - predeclared
    - goerr113 # Recommended
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - style
    # - unused
    # - bugs

linters-settings:
  # staticcheck:
  #  go: "1.13"

  #  checks: ["all"]

  # unused:
  #  go: "1.13"

issues:
  include:
    - EXC0002
