language: go
go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
install:
    - go get github.com/bwmarrin/discordgo
    - go get -v .
    - go get -v golang.org/x/lint/golint || true
script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint -set_exit_status ./... || true
    - go test -v -race ./...
