// Code generated by \"eventhandlers\"; DO NOT EDIT
// See events.go

package discordgo

import (
	"context"
)

// Following are all the event types.
// Event type values are used to match the events returned by Discord.
// EventTypes surrounded by __ are synthetic and are internal to DiscordGo.
const (
	channelCreateEventType            = "CHANNEL_CREATE"
	channelDeleteEventType            = "CHANNEL_DELETE"
	channelPinsUpdateEventType        = "CHANNEL_PINS_UPDATE"
	channelUpdateEventType            = "CHANNEL_UPDATE"
	connectEventType                  = "__CONNECT__"
	disconnectEventType               = "__DISCONNECT__"
	eventEventType                    = "__EVENT__"
	guildBanAddEventType              = "GUILD_BAN_ADD"
	guildBanRemoveEventType           = "GUILD_BAN_REMOVE"
	guildCreateEventType              = "GUILD_CREATE"
	guildDeleteEventType              = "GUILD_DELETE"
	guildEmojisUpdateEventType        = "GUILD_EMOJIS_UPDATE"
	guildIntegrationsUpdateEventType  = "GUILD_INTEGRATIONS_UPDATE"
	guildMemberAddEventType           = "GUILD_MEMBER_ADD"
	guildMemberRemoveEventType        = "GUILD_MEMBER_REMOVE"
	guildMemberUpdateEventType        = "GUILD_MEMBER_UPDATE"
	guildMembersChunkEventType        = "GUILD_MEMBERS_CHUNK"
	guildRoleCreateEventType          = "GUILD_ROLE_CREATE"
	guildRoleDeleteEventType          = "GUILD_ROLE_DELETE"
	guildRoleUpdateEventType          = "GUILD_ROLE_UPDATE"
	guildUpdateEventType              = "GUILD_UPDATE"
	messageAckEventType               = "MESSAGE_ACK"
	messageCreateEventType            = "MESSAGE_CREATE"
	messageDeleteEventType            = "MESSAGE_DELETE"
	messageDeleteBulkEventType        = "MESSAGE_DELETE_BULK"
	messageReactionAddEventType       = "MESSAGE_REACTION_ADD"
	messageReactionRemoveEventType    = "MESSAGE_REACTION_REMOVE"
	messageReactionRemoveAllEventType = "MESSAGE_REACTION_REMOVE_ALL"
	messageUpdateEventType            = "MESSAGE_UPDATE"
	presenceUpdateEventType           = "PRESENCE_UPDATE"
	presencesReplaceEventType         = "PRESENCES_REPLACE"
	rateLimitEventType                = "__RATE_LIMIT__"
	readyEventType                    = "READY"
	relationshipAddEventType          = "RELATIONSHIP_ADD"
	relationshipRemoveEventType       = "RELATIONSHIP_REMOVE"
	resumedEventType                  = "RESUMED"
	typingStartEventType              = "TYPING_START"
	userGuildSettingsUpdateEventType  = "USER_GUILD_SETTINGS_UPDATE"
	userNoteUpdateEventType           = "USER_NOTE_UPDATE"
	userSettingsUpdateEventType       = "USER_SETTINGS_UPDATE"
	userUpdateEventType               = "USER_UPDATE"
	voiceServerUpdateEventType        = "VOICE_SERVER_UPDATE"
	voiceStateUpdateEventType         = "VOICE_STATE_UPDATE"
)

// channelCreateEventHandler is an event handler for ChannelCreate events.
type channelCreateEventHandler func(context.Context, *Session, *ChannelCreate)

// Type returns the event type for ChannelCreate events.
func (eh channelCreateEventHandler) Type() string {
	return channelCreateEventType
}

// New returns a new instance of ChannelCreate.
func (eh channelCreateEventHandler) New() interface{} {
	return &ChannelCreate{}
}

// Handle is the handler for ChannelCreate events.
func (eh channelCreateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*ChannelCreate); ok {
		eh(c, s, t)
	}
}

// channelDeleteEventHandler is an event handler for ChannelDelete events.
type channelDeleteEventHandler func(context.Context, *Session, *ChannelDelete)

// Type returns the event type for ChannelDelete events.
func (eh channelDeleteEventHandler) Type() string {
	return channelDeleteEventType
}

// New returns a new instance of ChannelDelete.
func (eh channelDeleteEventHandler) New() interface{} {
	return &ChannelDelete{}
}

// Handle is the handler for ChannelDelete events.
func (eh channelDeleteEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*ChannelDelete); ok {
		eh(c, s, t)
	}
}

// channelPinsUpdateEventHandler is an event handler for ChannelPinsUpdate events.
type channelPinsUpdateEventHandler func(context.Context, *Session, *ChannelPinsUpdate)

// Type returns the event type for ChannelPinsUpdate events.
func (eh channelPinsUpdateEventHandler) Type() string {
	return channelPinsUpdateEventType
}

// New returns a new instance of ChannelPinsUpdate.
func (eh channelPinsUpdateEventHandler) New() interface{} {
	return &ChannelPinsUpdate{}
}

// Handle is the handler for ChannelPinsUpdate events.
func (eh channelPinsUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*ChannelPinsUpdate); ok {
		eh(c, s, t)
	}
}

// channelUpdateEventHandler is an event handler for ChannelUpdate events.
type channelUpdateEventHandler func(context.Context, *Session, *ChannelUpdate)

// Type returns the event type for ChannelUpdate events.
func (eh channelUpdateEventHandler) Type() string {
	return channelUpdateEventType
}

// New returns a new instance of ChannelUpdate.
func (eh channelUpdateEventHandler) New() interface{} {
	return &ChannelUpdate{}
}

// Handle is the handler for ChannelUpdate events.
func (eh channelUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*ChannelUpdate); ok {
		eh(c, s, t)
	}
}

// connectEventHandler is an event handler for Connect events.
type connectEventHandler func(context.Context, *Session, *Connect)

// Type returns the event type for Connect events.
func (eh connectEventHandler) Type() string {
	return connectEventType
}

// Handle is the handler for Connect events.
func (eh connectEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*Connect); ok {
		eh(c, s, t)
	}
}

// disconnectEventHandler is an event handler for Disconnect events.
type disconnectEventHandler func(context.Context, *Session, *Disconnect)

// Type returns the event type for Disconnect events.
func (eh disconnectEventHandler) Type() string {
	return disconnectEventType
}

// Handle is the handler for Disconnect events.
func (eh disconnectEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*Disconnect); ok {
		eh(c, s, t)
	}
}

// eventEventHandler is an event handler for Event events.
type eventEventHandler func(context.Context, *Session, *Event)

// Type returns the event type for Event events.
func (eh eventEventHandler) Type() string {
	return eventEventType
}

// Handle is the handler for Event events.
func (eh eventEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*Event); ok {
		eh(c, s, t)
	}
}

// guildBanAddEventHandler is an event handler for GuildBanAdd events.
type guildBanAddEventHandler func(context.Context, *Session, *GuildBanAdd)

// Type returns the event type for GuildBanAdd events.
func (eh guildBanAddEventHandler) Type() string {
	return guildBanAddEventType
}

// New returns a new instance of GuildBanAdd.
func (eh guildBanAddEventHandler) New() interface{} {
	return &GuildBanAdd{}
}

// Handle is the handler for GuildBanAdd events.
func (eh guildBanAddEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildBanAdd); ok {
		eh(c, s, t)
	}
}

// guildBanRemoveEventHandler is an event handler for GuildBanRemove events.
type guildBanRemoveEventHandler func(context.Context, *Session, *GuildBanRemove)

// Type returns the event type for GuildBanRemove events.
func (eh guildBanRemoveEventHandler) Type() string {
	return guildBanRemoveEventType
}

// New returns a new instance of GuildBanRemove.
func (eh guildBanRemoveEventHandler) New() interface{} {
	return &GuildBanRemove{}
}

// Handle is the handler for GuildBanRemove events.
func (eh guildBanRemoveEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildBanRemove); ok {
		eh(c, s, t)
	}
}

// guildCreateEventHandler is an event handler for GuildCreate events.
type guildCreateEventHandler func(context.Context, *Session, *GuildCreate)

// Type returns the event type for GuildCreate events.
func (eh guildCreateEventHandler) Type() string {
	return guildCreateEventType
}

// New returns a new instance of GuildCreate.
func (eh guildCreateEventHandler) New() interface{} {
	return &GuildCreate{}
}

// Handle is the handler for GuildCreate events.
func (eh guildCreateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildCreate); ok {
		eh(c, s, t)
	}
}

// guildDeleteEventHandler is an event handler for GuildDelete events.
type guildDeleteEventHandler func(context.Context, *Session, *GuildDelete)

// Type returns the event type for GuildDelete events.
func (eh guildDeleteEventHandler) Type() string {
	return guildDeleteEventType
}

// New returns a new instance of GuildDelete.
func (eh guildDeleteEventHandler) New() interface{} {
	return &GuildDelete{}
}

// Handle is the handler for GuildDelete events.
func (eh guildDeleteEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildDelete); ok {
		eh(c, s, t)
	}
}

// guildEmojisUpdateEventHandler is an event handler for GuildEmojisUpdate events.
type guildEmojisUpdateEventHandler func(context.Context, *Session, *GuildEmojisUpdate)

// Type returns the event type for GuildEmojisUpdate events.
func (eh guildEmojisUpdateEventHandler) Type() string {
	return guildEmojisUpdateEventType
}

// New returns a new instance of GuildEmojisUpdate.
func (eh guildEmojisUpdateEventHandler) New() interface{} {
	return &GuildEmojisUpdate{}
}

// Handle is the handler for GuildEmojisUpdate events.
func (eh guildEmojisUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildEmojisUpdate); ok {
		eh(c, s, t)
	}
}

// guildIntegrationsUpdateEventHandler is an event handler for GuildIntegrationsUpdate events.
type guildIntegrationsUpdateEventHandler func(context.Context, *Session, *GuildIntegrationsUpdate)

// Type returns the event type for GuildIntegrationsUpdate events.
func (eh guildIntegrationsUpdateEventHandler) Type() string {
	return guildIntegrationsUpdateEventType
}

// New returns a new instance of GuildIntegrationsUpdate.
func (eh guildIntegrationsUpdateEventHandler) New() interface{} {
	return &GuildIntegrationsUpdate{}
}

// Handle is the handler for GuildIntegrationsUpdate events.
func (eh guildIntegrationsUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildIntegrationsUpdate); ok {
		eh(c, s, t)
	}
}

// guildMemberAddEventHandler is an event handler for GuildMemberAdd events.
type guildMemberAddEventHandler func(context.Context, *Session, *GuildMemberAdd)

// Type returns the event type for GuildMemberAdd events.
func (eh guildMemberAddEventHandler) Type() string {
	return guildMemberAddEventType
}

// New returns a new instance of GuildMemberAdd.
func (eh guildMemberAddEventHandler) New() interface{} {
	return &GuildMemberAdd{}
}

// Handle is the handler for GuildMemberAdd events.
func (eh guildMemberAddEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildMemberAdd); ok {
		eh(c, s, t)
	}
}

// guildMemberRemoveEventHandler is an event handler for GuildMemberRemove events.
type guildMemberRemoveEventHandler func(context.Context, *Session, *GuildMemberRemove)

// Type returns the event type for GuildMemberRemove events.
func (eh guildMemberRemoveEventHandler) Type() string {
	return guildMemberRemoveEventType
}

// New returns a new instance of GuildMemberRemove.
func (eh guildMemberRemoveEventHandler) New() interface{} {
	return &GuildMemberRemove{}
}

// Handle is the handler for GuildMemberRemove events.
func (eh guildMemberRemoveEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildMemberRemove); ok {
		eh(c, s, t)
	}
}

// guildMemberUpdateEventHandler is an event handler for GuildMemberUpdate events.
type guildMemberUpdateEventHandler func(context.Context, *Session, *GuildMemberUpdate)

// Type returns the event type for GuildMemberUpdate events.
func (eh guildMemberUpdateEventHandler) Type() string {
	return guildMemberUpdateEventType
}

// New returns a new instance of GuildMemberUpdate.
func (eh guildMemberUpdateEventHandler) New() interface{} {
	return &GuildMemberUpdate{}
}

// Handle is the handler for GuildMemberUpdate events.
func (eh guildMemberUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildMemberUpdate); ok {
		eh(c, s, t)
	}
}

// guildMembersChunkEventHandler is an event handler for GuildMembersChunk events.
type guildMembersChunkEventHandler func(context.Context, *Session, *GuildMembersChunk)

// Type returns the event type for GuildMembersChunk events.
func (eh guildMembersChunkEventHandler) Type() string {
	return guildMembersChunkEventType
}

// New returns a new instance of GuildMembersChunk.
func (eh guildMembersChunkEventHandler) New() interface{} {
	return &GuildMembersChunk{}
}

// Handle is the handler for GuildMembersChunk events.
func (eh guildMembersChunkEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildMembersChunk); ok {
		eh(c, s, t)
	}
}

// guildRoleCreateEventHandler is an event handler for GuildRoleCreate events.
type guildRoleCreateEventHandler func(context.Context, *Session, *GuildRoleCreate)

// Type returns the event type for GuildRoleCreate events.
func (eh guildRoleCreateEventHandler) Type() string {
	return guildRoleCreateEventType
}

// New returns a new instance of GuildRoleCreate.
func (eh guildRoleCreateEventHandler) New() interface{} {
	return &GuildRoleCreate{}
}

// Handle is the handler for GuildRoleCreate events.
func (eh guildRoleCreateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildRoleCreate); ok {
		eh(c, s, t)
	}
}

// guildRoleDeleteEventHandler is an event handler for GuildRoleDelete events.
type guildRoleDeleteEventHandler func(context.Context, *Session, *GuildRoleDelete)

// Type returns the event type for GuildRoleDelete events.
func (eh guildRoleDeleteEventHandler) Type() string {
	return guildRoleDeleteEventType
}

// New returns a new instance of GuildRoleDelete.
func (eh guildRoleDeleteEventHandler) New() interface{} {
	return &GuildRoleDelete{}
}

// Handle is the handler for GuildRoleDelete events.
func (eh guildRoleDeleteEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildRoleDelete); ok {
		eh(c, s, t)
	}
}

// guildRoleUpdateEventHandler is an event handler for GuildRoleUpdate events.
type guildRoleUpdateEventHandler func(context.Context, *Session, *GuildRoleUpdate)

// Type returns the event type for GuildRoleUpdate events.
func (eh guildRoleUpdateEventHandler) Type() string {
	return guildRoleUpdateEventType
}

// New returns a new instance of GuildRoleUpdate.
func (eh guildRoleUpdateEventHandler) New() interface{} {
	return &GuildRoleUpdate{}
}

// Handle is the handler for GuildRoleUpdate events.
func (eh guildRoleUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildRoleUpdate); ok {
		eh(c, s, t)
	}
}

// guildUpdateEventHandler is an event handler for GuildUpdate events.
type guildUpdateEventHandler func(context.Context, *Session, *GuildUpdate)

// Type returns the event type for GuildUpdate events.
func (eh guildUpdateEventHandler) Type() string {
	return guildUpdateEventType
}

// New returns a new instance of GuildUpdate.
func (eh guildUpdateEventHandler) New() interface{} {
	return &GuildUpdate{}
}

// Handle is the handler for GuildUpdate events.
func (eh guildUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*GuildUpdate); ok {
		eh(c, s, t)
	}
}

// messageAckEventHandler is an event handler for MessageAck events.
type messageAckEventHandler func(context.Context, *Session, *MessageAck)

// Type returns the event type for MessageAck events.
func (eh messageAckEventHandler) Type() string {
	return messageAckEventType
}

// New returns a new instance of MessageAck.
func (eh messageAckEventHandler) New() interface{} {
	return &MessageAck{}
}

// Handle is the handler for MessageAck events.
func (eh messageAckEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageAck); ok {
		eh(c, s, t)
	}
}

// messageCreateEventHandler is an event handler for MessageCreate events.
type messageCreateEventHandler func(context.Context, *Session, *MessageCreate)

// Type returns the event type for MessageCreate events.
func (eh messageCreateEventHandler) Type() string {
	return messageCreateEventType
}

// New returns a new instance of MessageCreate.
func (eh messageCreateEventHandler) New() interface{} {
	return &MessageCreate{}
}

// Handle is the handler for MessageCreate events.
func (eh messageCreateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageCreate); ok {
		eh(c, s, t)
	}
}

// messageDeleteEventHandler is an event handler for MessageDelete events.
type messageDeleteEventHandler func(context.Context, *Session, *MessageDelete)

// Type returns the event type for MessageDelete events.
func (eh messageDeleteEventHandler) Type() string {
	return messageDeleteEventType
}

// New returns a new instance of MessageDelete.
func (eh messageDeleteEventHandler) New() interface{} {
	return &MessageDelete{}
}

// Handle is the handler for MessageDelete events.
func (eh messageDeleteEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageDelete); ok {
		eh(c, s, t)
	}
}

// messageDeleteBulkEventHandler is an event handler for MessageDeleteBulk events.
type messageDeleteBulkEventHandler func(context.Context, *Session, *MessageDeleteBulk)

// Type returns the event type for MessageDeleteBulk events.
func (eh messageDeleteBulkEventHandler) Type() string {
	return messageDeleteBulkEventType
}

// New returns a new instance of MessageDeleteBulk.
func (eh messageDeleteBulkEventHandler) New() interface{} {
	return &MessageDeleteBulk{}
}

// Handle is the handler for MessageDeleteBulk events.
func (eh messageDeleteBulkEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageDeleteBulk); ok {
		eh(c, s, t)
	}
}

// messageReactionAddEventHandler is an event handler for MessageReactionAdd events.
type messageReactionAddEventHandler func(context.Context, *Session, *MessageReactionAdd)

// Type returns the event type for MessageReactionAdd events.
func (eh messageReactionAddEventHandler) Type() string {
	return messageReactionAddEventType
}

// New returns a new instance of MessageReactionAdd.
func (eh messageReactionAddEventHandler) New() interface{} {
	return &MessageReactionAdd{}
}

// Handle is the handler for MessageReactionAdd events.
func (eh messageReactionAddEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageReactionAdd); ok {
		eh(c, s, t)
	}
}

// messageReactionRemoveEventHandler is an event handler for MessageReactionRemove events.
type messageReactionRemoveEventHandler func(context.Context, *Session, *MessageReactionRemove)

// Type returns the event type for MessageReactionRemove events.
func (eh messageReactionRemoveEventHandler) Type() string {
	return messageReactionRemoveEventType
}

// New returns a new instance of MessageReactionRemove.
func (eh messageReactionRemoveEventHandler) New() interface{} {
	return &MessageReactionRemove{}
}

// Handle is the handler for MessageReactionRemove events.
func (eh messageReactionRemoveEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageReactionRemove); ok {
		eh(c, s, t)
	}
}

// messageReactionRemoveAllEventHandler is an event handler for MessageReactionRemoveAll events.
type messageReactionRemoveAllEventHandler func(context.Context, *Session, *MessageReactionRemoveAll)

// Type returns the event type for MessageReactionRemoveAll events.
func (eh messageReactionRemoveAllEventHandler) Type() string {
	return messageReactionRemoveAllEventType
}

// New returns a new instance of MessageReactionRemoveAll.
func (eh messageReactionRemoveAllEventHandler) New() interface{} {
	return &MessageReactionRemoveAll{}
}

// Handle is the handler for MessageReactionRemoveAll events.
func (eh messageReactionRemoveAllEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageReactionRemoveAll); ok {
		eh(c, s, t)
	}
}

// messageUpdateEventHandler is an event handler for MessageUpdate events.
type messageUpdateEventHandler func(context.Context, *Session, *MessageUpdate)

// Type returns the event type for MessageUpdate events.
func (eh messageUpdateEventHandler) Type() string {
	return messageUpdateEventType
}

// New returns a new instance of MessageUpdate.
func (eh messageUpdateEventHandler) New() interface{} {
	return &MessageUpdate{}
}

// Handle is the handler for MessageUpdate events.
func (eh messageUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*MessageUpdate); ok {
		eh(c, s, t)
	}
}

// presenceUpdateEventHandler is an event handler for PresenceUpdate events.
type presenceUpdateEventHandler func(context.Context, *Session, *PresenceUpdate)

// Type returns the event type for PresenceUpdate events.
func (eh presenceUpdateEventHandler) Type() string {
	return presenceUpdateEventType
}

// New returns a new instance of PresenceUpdate.
func (eh presenceUpdateEventHandler) New() interface{} {
	return &PresenceUpdate{}
}

// Handle is the handler for PresenceUpdate events.
func (eh presenceUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*PresenceUpdate); ok {
		eh(c, s, t)
	}
}

// presencesReplaceEventHandler is an event handler for PresencesReplace events.
type presencesReplaceEventHandler func(context.Context, *Session, *PresencesReplace)

// Type returns the event type for PresencesReplace events.
func (eh presencesReplaceEventHandler) Type() string {
	return presencesReplaceEventType
}

// New returns a new instance of PresencesReplace.
func (eh presencesReplaceEventHandler) New() interface{} {
	return &PresencesReplace{}
}

// Handle is the handler for PresencesReplace events.
func (eh presencesReplaceEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*PresencesReplace); ok {
		eh(c, s, t)
	}
}

// rateLimitEventHandler is an event handler for RateLimit events.
type rateLimitEventHandler func(context.Context, *Session, *RateLimit)

// Type returns the event type for RateLimit events.
func (eh rateLimitEventHandler) Type() string {
	return rateLimitEventType
}

// Handle is the handler for RateLimit events.
func (eh rateLimitEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*RateLimit); ok {
		eh(c, s, t)
	}
}

// readyEventHandler is an event handler for Ready events.
type readyEventHandler func(context.Context, *Session, *Ready)

// Type returns the event type for Ready events.
func (eh readyEventHandler) Type() string {
	return readyEventType
}

// New returns a new instance of Ready.
func (eh readyEventHandler) New() interface{} {
	return &Ready{}
}

// Handle is the handler for Ready events.
func (eh readyEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*Ready); ok {
		eh(c, s, t)
	}
}

// relationshipAddEventHandler is an event handler for RelationshipAdd events.
type relationshipAddEventHandler func(context.Context, *Session, *RelationshipAdd)

// Type returns the event type for RelationshipAdd events.
func (eh relationshipAddEventHandler) Type() string {
	return relationshipAddEventType
}

// New returns a new instance of RelationshipAdd.
func (eh relationshipAddEventHandler) New() interface{} {
	return &RelationshipAdd{}
}

// Handle is the handler for RelationshipAdd events.
func (eh relationshipAddEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*RelationshipAdd); ok {
		eh(c, s, t)
	}
}

// relationshipRemoveEventHandler is an event handler for RelationshipRemove events.
type relationshipRemoveEventHandler func(context.Context, *Session, *RelationshipRemove)

// Type returns the event type for RelationshipRemove events.
func (eh relationshipRemoveEventHandler) Type() string {
	return relationshipRemoveEventType
}

// New returns a new instance of RelationshipRemove.
func (eh relationshipRemoveEventHandler) New() interface{} {
	return &RelationshipRemove{}
}

// Handle is the handler for RelationshipRemove events.
func (eh relationshipRemoveEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*RelationshipRemove); ok {
		eh(c, s, t)
	}
}

// resumedEventHandler is an event handler for Resumed events.
type resumedEventHandler func(context.Context, *Session, *Resumed)

// Type returns the event type for Resumed events.
func (eh resumedEventHandler) Type() string {
	return resumedEventType
}

// New returns a new instance of Resumed.
func (eh resumedEventHandler) New() interface{} {
	return &Resumed{}
}

// Handle is the handler for Resumed events.
func (eh resumedEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*Resumed); ok {
		eh(c, s, t)
	}
}

// typingStartEventHandler is an event handler for TypingStart events.
type typingStartEventHandler func(context.Context, *Session, *TypingStart)

// Type returns the event type for TypingStart events.
func (eh typingStartEventHandler) Type() string {
	return typingStartEventType
}

// New returns a new instance of TypingStart.
func (eh typingStartEventHandler) New() interface{} {
	return &TypingStart{}
}

// Handle is the handler for TypingStart events.
func (eh typingStartEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*TypingStart); ok {
		eh(c, s, t)
	}
}

// userGuildSettingsUpdateEventHandler is an event handler for UserGuildSettingsUpdate events.
type userGuildSettingsUpdateEventHandler func(context.Context, *Session, *UserGuildSettingsUpdate)

// Type returns the event type for UserGuildSettingsUpdate events.
func (eh userGuildSettingsUpdateEventHandler) Type() string {
	return userGuildSettingsUpdateEventType
}

// New returns a new instance of UserGuildSettingsUpdate.
func (eh userGuildSettingsUpdateEventHandler) New() interface{} {
	return &UserGuildSettingsUpdate{}
}

// Handle is the handler for UserGuildSettingsUpdate events.
func (eh userGuildSettingsUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*UserGuildSettingsUpdate); ok {
		eh(c, s, t)
	}
}

// userNoteUpdateEventHandler is an event handler for UserNoteUpdate events.
type userNoteUpdateEventHandler func(context.Context, *Session, *UserNoteUpdate)

// Type returns the event type for UserNoteUpdate events.
func (eh userNoteUpdateEventHandler) Type() string {
	return userNoteUpdateEventType
}

// New returns a new instance of UserNoteUpdate.
func (eh userNoteUpdateEventHandler) New() interface{} {
	return &UserNoteUpdate{}
}

// Handle is the handler for UserNoteUpdate events.
func (eh userNoteUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*UserNoteUpdate); ok {
		eh(c, s, t)
	}
}

// userSettingsUpdateEventHandler is an event handler for UserSettingsUpdate events.
type userSettingsUpdateEventHandler func(context.Context, *Session, *UserSettingsUpdate)

// Type returns the event type for UserSettingsUpdate events.
func (eh userSettingsUpdateEventHandler) Type() string {
	return userSettingsUpdateEventType
}

// New returns a new instance of UserSettingsUpdate.
func (eh userSettingsUpdateEventHandler) New() interface{} {
	return &UserSettingsUpdate{}
}

// Handle is the handler for UserSettingsUpdate events.
func (eh userSettingsUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*UserSettingsUpdate); ok {
		eh(c, s, t)
	}
}

// userUpdateEventHandler is an event handler for UserUpdate events.
type userUpdateEventHandler func(context.Context, *Session, *UserUpdate)

// Type returns the event type for UserUpdate events.
func (eh userUpdateEventHandler) Type() string {
	return userUpdateEventType
}

// New returns a new instance of UserUpdate.
func (eh userUpdateEventHandler) New() interface{} {
	return &UserUpdate{}
}

// Handle is the handler for UserUpdate events.
func (eh userUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*UserUpdate); ok {
		eh(c, s, t)
	}
}

// voiceServerUpdateEventHandler is an event handler for VoiceServerUpdate events.
type voiceServerUpdateEventHandler func(context.Context, *Session, *VoiceServerUpdate)

// Type returns the event type for VoiceServerUpdate events.
func (eh voiceServerUpdateEventHandler) Type() string {
	return voiceServerUpdateEventType
}

// New returns a new instance of VoiceServerUpdate.
func (eh voiceServerUpdateEventHandler) New() interface{} {
	return &VoiceServerUpdate{}
}

// Handle is the handler for VoiceServerUpdate events.
func (eh voiceServerUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*VoiceServerUpdate); ok {
		eh(c, s, t)
	}
}

// voiceStateUpdateEventHandler is an event handler for VoiceStateUpdate events.
type voiceStateUpdateEventHandler func(context.Context, *Session, *VoiceStateUpdate)

// Type returns the event type for VoiceStateUpdate events.
func (eh voiceStateUpdateEventHandler) Type() string {
	return voiceStateUpdateEventType
}

// New returns a new instance of VoiceStateUpdate.
func (eh voiceStateUpdateEventHandler) New() interface{} {
	return &VoiceStateUpdate{}
}

// Handle is the handler for VoiceStateUpdate events.
func (eh voiceStateUpdateEventHandler) Handle(c context.Context, s *Session, i interface{}) {
	if t, ok := i.(*VoiceStateUpdate); ok {
		eh(c, s, t)
	}
}

func handlerForInterface(handler interface{}) EventHandler {
	switch v := handler.(type) {
	case func(context.Context, *Session, interface{}):
		return interfaceEventHandler(v)
	case func(context.Context, *Session, *ChannelCreate):
		return channelCreateEventHandler(v)
	case func(context.Context, *Session, *ChannelDelete):
		return channelDeleteEventHandler(v)
	case func(context.Context, *Session, *ChannelPinsUpdate):
		return channelPinsUpdateEventHandler(v)
	case func(context.Context, *Session, *ChannelUpdate):
		return channelUpdateEventHandler(v)
	case func(context.Context, *Session, *Connect):
		return connectEventHandler(v)
	case func(context.Context, *Session, *Disconnect):
		return disconnectEventHandler(v)
	case func(context.Context, *Session, *Event):
		return eventEventHandler(v)
	case func(context.Context, *Session, *GuildBanAdd):
		return guildBanAddEventHandler(v)
	case func(context.Context, *Session, *GuildBanRemove):
		return guildBanRemoveEventHandler(v)
	case func(context.Context, *Session, *GuildCreate):
		return guildCreateEventHandler(v)
	case func(context.Context, *Session, *GuildDelete):
		return guildDeleteEventHandler(v)
	case func(context.Context, *Session, *GuildEmojisUpdate):
		return guildEmojisUpdateEventHandler(v)
	case func(context.Context, *Session, *GuildIntegrationsUpdate):
		return guildIntegrationsUpdateEventHandler(v)
	case func(context.Context, *Session, *GuildMemberAdd):
		return guildMemberAddEventHandler(v)
	case func(context.Context, *Session, *GuildMemberRemove):
		return guildMemberRemoveEventHandler(v)
	case func(context.Context, *Session, *GuildMemberUpdate):
		return guildMemberUpdateEventHandler(v)
	case func(context.Context, *Session, *GuildMembersChunk):
		return guildMembersChunkEventHandler(v)
	case func(context.Context, *Session, *GuildRoleCreate):
		return guildRoleCreateEventHandler(v)
	case func(context.Context, *Session, *GuildRoleDelete):
		return guildRoleDeleteEventHandler(v)
	case func(context.Context, *Session, *GuildRoleUpdate):
		return guildRoleUpdateEventHandler(v)
	case func(context.Context, *Session, *GuildUpdate):
		return guildUpdateEventHandler(v)
	case func(context.Context, *Session, *MessageAck):
		return messageAckEventHandler(v)
	case func(context.Context, *Session, *MessageCreate):
		return messageCreateEventHandler(v)
	case func(context.Context, *Session, *MessageDelete):
		return messageDeleteEventHandler(v)
	case func(context.Context, *Session, *MessageDeleteBulk):
		return messageDeleteBulkEventHandler(v)
	case func(context.Context, *Session, *MessageReactionAdd):
		return messageReactionAddEventHandler(v)
	case func(context.Context, *Session, *MessageReactionRemove):
		return messageReactionRemoveEventHandler(v)
	case func(context.Context, *Session, *MessageReactionRemoveAll):
		return messageReactionRemoveAllEventHandler(v)
	case func(context.Context, *Session, *MessageUpdate):
		return messageUpdateEventHandler(v)
	case func(context.Context, *Session, *PresenceUpdate):
		return presenceUpdateEventHandler(v)
	case func(context.Context, *Session, *PresencesReplace):
		return presencesReplaceEventHandler(v)
	case func(context.Context, *Session, *RateLimit):
		return rateLimitEventHandler(v)
	case func(context.Context, *Session, *Ready):
		return readyEventHandler(v)
	case func(context.Context, *Session, *RelationshipAdd):
		return relationshipAddEventHandler(v)
	case func(context.Context, *Session, *RelationshipRemove):
		return relationshipRemoveEventHandler(v)
	case func(context.Context, *Session, *Resumed):
		return resumedEventHandler(v)
	case func(context.Context, *Session, *TypingStart):
		return typingStartEventHandler(v)
	case func(context.Context, *Session, *UserGuildSettingsUpdate):
		return userGuildSettingsUpdateEventHandler(v)
	case func(context.Context, *Session, *UserNoteUpdate):
		return userNoteUpdateEventHandler(v)
	case func(context.Context, *Session, *UserSettingsUpdate):
		return userSettingsUpdateEventHandler(v)
	case func(context.Context, *Session, *UserUpdate):
		return userUpdateEventHandler(v)
	case func(context.Context, *Session, *VoiceServerUpdate):
		return voiceServerUpdateEventHandler(v)
	case func(context.Context, *Session, *VoiceStateUpdate):
		return voiceStateUpdateEventHandler(v)
	case func(*Session, interface{}):
		w := func(_ context.Context, s *Session, i interface{}) { v(s, i) }
		return interfaceEventHandler(w)
	case func(*Session, *ChannelCreate):
		w := func(_ context.Context, s *Session, i *ChannelCreate) { v(s, i) }
		return channelCreateEventHandler(w)
	case func(*Session, *ChannelDelete):
		w := func(_ context.Context, s *Session, i *ChannelDelete) { v(s, i) }
		return channelDeleteEventHandler(w)
	case func(*Session, *ChannelPinsUpdate):
		w := func(_ context.Context, s *Session, i *ChannelPinsUpdate) { v(s, i) }
		return channelPinsUpdateEventHandler(w)
	case func(*Session, *ChannelUpdate):
		w := func(_ context.Context, s *Session, i *ChannelUpdate) { v(s, i) }
		return channelUpdateEventHandler(w)
	case func(*Session, *Connect):
		w := func(_ context.Context, s *Session, i *Connect) { v(s, i) }
		return connectEventHandler(w)
	case func(*Session, *Disconnect):
		w := func(_ context.Context, s *Session, i *Disconnect) { v(s, i) }
		return disconnectEventHandler(w)
	case func(*Session, *Event):
		w := func(_ context.Context, s *Session, i *Event) { v(s, i) }
		return eventEventHandler(w)
	case func(*Session, *GuildBanAdd):
		w := func(_ context.Context, s *Session, i *GuildBanAdd) { v(s, i) }
		return guildBanAddEventHandler(w)
	case func(*Session, *GuildBanRemove):
		w := func(_ context.Context, s *Session, i *GuildBanRemove) { v(s, i) }
		return guildBanRemoveEventHandler(w)
	case func(*Session, *GuildCreate):
		w := func(_ context.Context, s *Session, i *GuildCreate) { v(s, i) }
		return guildCreateEventHandler(w)
	case func(*Session, *GuildDelete):
		w := func(_ context.Context, s *Session, i *GuildDelete) { v(s, i) }
		return guildDeleteEventHandler(w)
	case func(*Session, *GuildEmojisUpdate):
		w := func(_ context.Context, s *Session, i *GuildEmojisUpdate) { v(s, i) }
		return guildEmojisUpdateEventHandler(w)
	case func(*Session, *GuildIntegrationsUpdate):
		w := func(_ context.Context, s *Session, i *GuildIntegrationsUpdate) { v(s, i) }
		return guildIntegrationsUpdateEventHandler(w)
	case func(*Session, *GuildMemberAdd):
		w := func(_ context.Context, s *Session, i *GuildMemberAdd) { v(s, i) }
		return guildMemberAddEventHandler(w)
	case func(*Session, *GuildMemberRemove):
		w := func(_ context.Context, s *Session, i *GuildMemberRemove) { v(s, i) }
		return guildMemberRemoveEventHandler(w)
	case func(*Session, *GuildMemberUpdate):
		w := func(_ context.Context, s *Session, i *GuildMemberUpdate) { v(s, i) }
		return guildMemberUpdateEventHandler(w)
	case func(*Session, *GuildMembersChunk):
		w := func(_ context.Context, s *Session, i *GuildMembersChunk) { v(s, i) }
		return guildMembersChunkEventHandler(w)
	case func(*Session, *GuildRoleCreate):
		w := func(_ context.Context, s *Session, i *GuildRoleCreate) { v(s, i) }
		return guildRoleCreateEventHandler(w)
	case func(*Session, *GuildRoleDelete):
		w := func(_ context.Context, s *Session, i *GuildRoleDelete) { v(s, i) }
		return guildRoleDeleteEventHandler(w)
	case func(*Session, *GuildRoleUpdate):
		w := func(_ context.Context, s *Session, i *GuildRoleUpdate) { v(s, i) }
		return guildRoleUpdateEventHandler(w)
	case func(*Session, *GuildUpdate):
		w := func(_ context.Context, s *Session, i *GuildUpdate) { v(s, i) }
		return guildUpdateEventHandler(w)
	case func(*Session, *MessageAck):
		w := func(_ context.Context, s *Session, i *MessageAck) { v(s, i) }
		return messageAckEventHandler(w)
	case func(*Session, *MessageCreate):
		w := func(_ context.Context, s *Session, i *MessageCreate) { v(s, i) }
		return messageCreateEventHandler(w)
	case func(*Session, *MessageDelete):
		w := func(_ context.Context, s *Session, i *MessageDelete) { v(s, i) }
		return messageDeleteEventHandler(w)
	case func(*Session, *MessageDeleteBulk):
		w := func(_ context.Context, s *Session, i *MessageDeleteBulk) { v(s, i) }
		return messageDeleteBulkEventHandler(w)
	case func(*Session, *MessageReactionAdd):
		w := func(_ context.Context, s *Session, i *MessageReactionAdd) { v(s, i) }
		return messageReactionAddEventHandler(w)
	case func(*Session, *MessageReactionRemove):
		w := func(_ context.Context, s *Session, i *MessageReactionRemove) { v(s, i) }
		return messageReactionRemoveEventHandler(w)
	case func(*Session, *MessageReactionRemoveAll):
		w := func(_ context.Context, s *Session, i *MessageReactionRemoveAll) { v(s, i) }
		return messageReactionRemoveAllEventHandler(w)
	case func(*Session, *MessageUpdate):
		w := func(_ context.Context, s *Session, i *MessageUpdate) { v(s, i) }
		return messageUpdateEventHandler(w)
	case func(*Session, *PresenceUpdate):
		w := func(_ context.Context, s *Session, i *PresenceUpdate) { v(s, i) }
		return presenceUpdateEventHandler(w)
	case func(*Session, *PresencesReplace):
		w := func(_ context.Context, s *Session, i *PresencesReplace) { v(s, i) }
		return presencesReplaceEventHandler(w)
	case func(*Session, *RateLimit):
		w := func(_ context.Context, s *Session, i *RateLimit) { v(s, i) }
		return rateLimitEventHandler(w)
	case func(*Session, *Ready):
		w := func(_ context.Context, s *Session, i *Ready) { v(s, i) }
		return readyEventHandler(w)
	case func(*Session, *RelationshipAdd):
		w := func(_ context.Context, s *Session, i *RelationshipAdd) { v(s, i) }
		return relationshipAddEventHandler(w)
	case func(*Session, *RelationshipRemove):
		w := func(_ context.Context, s *Session, i *RelationshipRemove) { v(s, i) }
		return relationshipRemoveEventHandler(w)
	case func(*Session, *Resumed):
		w := func(_ context.Context, s *Session, i *Resumed) { v(s, i) }
		return resumedEventHandler(w)
	case func(*Session, *TypingStart):
		w := func(_ context.Context, s *Session, i *TypingStart) { v(s, i) }
		return typingStartEventHandler(w)
	case func(*Session, *UserGuildSettingsUpdate):
		w := func(_ context.Context, s *Session, i *UserGuildSettingsUpdate) { v(s, i) }
		return userGuildSettingsUpdateEventHandler(w)
	case func(*Session, *UserNoteUpdate):
		w := func(_ context.Context, s *Session, i *UserNoteUpdate) { v(s, i) }
		return userNoteUpdateEventHandler(w)
	case func(*Session, *UserSettingsUpdate):
		w := func(_ context.Context, s *Session, i *UserSettingsUpdate) { v(s, i) }
		return userSettingsUpdateEventHandler(w)
	case func(*Session, *UserUpdate):
		w := func(_ context.Context, s *Session, i *UserUpdate) { v(s, i) }
		return userUpdateEventHandler(w)
	case func(*Session, *VoiceServerUpdate):
		w := func(_ context.Context, s *Session, i *VoiceServerUpdate) { v(s, i) }
		return voiceServerUpdateEventHandler(w)
	case func(*Session, *VoiceStateUpdate):
		w := func(_ context.Context, s *Session, i *VoiceStateUpdate) { v(s, i) }
		return voiceStateUpdateEventHandler(w)
	}

	return nil
}

func init() {
	registerInterfaceProvider(channelCreateEventHandler(nil))
	registerInterfaceProvider(channelDeleteEventHandler(nil))
	registerInterfaceProvider(channelPinsUpdateEventHandler(nil))
	registerInterfaceProvider(channelUpdateEventHandler(nil))
	registerInterfaceProvider(guildBanAddEventHandler(nil))
	registerInterfaceProvider(guildBanRemoveEventHandler(nil))
	registerInterfaceProvider(guildCreateEventHandler(nil))
	registerInterfaceProvider(guildDeleteEventHandler(nil))
	registerInterfaceProvider(guildEmojisUpdateEventHandler(nil))
	registerInterfaceProvider(guildIntegrationsUpdateEventHandler(nil))
	registerInterfaceProvider(guildMemberAddEventHandler(nil))
	registerInterfaceProvider(guildMemberRemoveEventHandler(nil))
	registerInterfaceProvider(guildMemberUpdateEventHandler(nil))
	registerInterfaceProvider(guildMembersChunkEventHandler(nil))
	registerInterfaceProvider(guildRoleCreateEventHandler(nil))
	registerInterfaceProvider(guildRoleDeleteEventHandler(nil))
	registerInterfaceProvider(guildRoleUpdateEventHandler(nil))
	registerInterfaceProvider(guildUpdateEventHandler(nil))
	registerInterfaceProvider(messageAckEventHandler(nil))
	registerInterfaceProvider(messageCreateEventHandler(nil))
	registerInterfaceProvider(messageDeleteEventHandler(nil))
	registerInterfaceProvider(messageDeleteBulkEventHandler(nil))
	registerInterfaceProvider(messageReactionAddEventHandler(nil))
	registerInterfaceProvider(messageReactionRemoveEventHandler(nil))
	registerInterfaceProvider(messageReactionRemoveAllEventHandler(nil))
	registerInterfaceProvider(messageUpdateEventHandler(nil))
	registerInterfaceProvider(presenceUpdateEventHandler(nil))
	registerInterfaceProvider(presencesReplaceEventHandler(nil))
	registerInterfaceProvider(readyEventHandler(nil))
	registerInterfaceProvider(relationshipAddEventHandler(nil))
	registerInterfaceProvider(relationshipRemoveEventHandler(nil))
	registerInterfaceProvider(resumedEventHandler(nil))
	registerInterfaceProvider(typingStartEventHandler(nil))
	registerInterfaceProvider(userGuildSettingsUpdateEventHandler(nil))
	registerInterfaceProvider(userNoteUpdateEventHandler(nil))
	registerInterfaceProvider(userSettingsUpdateEventHandler(nil))
	registerInterfaceProvider(userUpdateEventHandler(nil))
	registerInterfaceProvider(voiceServerUpdateEventHandler(nil))
	registerInterfaceProvider(voiceStateUpdateEventHandler(nil))
}
